name: Generate Podcast Feeds
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Reppo
        uses: actions/checkout@v3
      - name: Run Feed Generator
        uses: DogiDev/podcast-generator@main
